Modified hbcgen script and added 2 new ones, one for libraries, and one a universal python script

diff --git a/hbcgen b/hbcgen
--- a/hbcgen
+++ b/hbcgen
@@ -11,6 +11,7 @@ SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
 ORG_DIR=$(pwd)
 cd $1
 echo "Switching to path:" $(pwd)
+mkdir hbcgen_logs
 
 # Ensure the project directory is a nodejs directory
 if [ ! -f "./package.json" ]
@@ -19,22 +20,27 @@ if [ ! -f "./package.json" ]
     exit 1
 fi
 
-# Install required npm library components
-echo "-------------------------------------------------------------------------"
-echo "Installing npm library packages:" $(pwd)
-echo "-------------------------------------------------------------------------"
-npm install
+echo "Converting react-native project in '$1' to Hermes Byte Code:"
 
-# Build code bundle from project
-echo "-------------------------------------------------------------------------"
-echo "Building code bundle --> index.android.bundle"
-echo "-------------------------------------------------------------------------"
-npx react-native bundle --dev false --platform android --entry-file $2 --bundle-output ./index.android.bundle --minify false
+# Install required npm library components
+echo -n "  Installing npm library packages..."
+npm install --force > ./hbcgen_logs/npm_install.log 2>&1
 if [ ! $? ]
   then
-    echo "Error: Failed to build code bundle"
+    echo; echo "Error: Failed to install npm packages, see logs in '$1/hbcgen_logs/npm_install.log'"
     exit 1
 fi
+echo " DONE"
+
+# Build code bundle from project
+echo -n "  Building code bundle from '$2' to 'index.android.bundle'..."
+npx react-native bundle --dev false --platform android --entry-file $2 --bundle-output ./index.android.bundle --minify false > ./hbcgen_logs/bundle_js.log 2>&1
+if [ ! $? ]
+  then
+    echo; echo "Error: Failed to build code bundle, see logs in '$1/hbcgen_logs/bundle_js.log'"
+    exit 1
+fi
+echo " DONE"
 
 # Ensure that hermes engine was installed by npm
 if [ ! -e "./node_modules/hermes-engine" ]
@@ -50,29 +56,27 @@ if [ ! $? ]
     echo "Error: Could not determine hermes bytecode version"
     exit 1
 fi
-echo "-------------------------------------------------------------------------"
-echo "Detected project hermes version:" $PROJ_HBC
+echo "  Detected project hermes version: $PROJ_HBC"
 
 # Compile js bundle into hermes binary
-echo "Assembling js bundle into hermes binary --> index.android.bundle.hbc"
-echo "-------------------------------------------------------------------------"
-./node_modules/hermes-engine/linux64-bin/hermesc -O -emit-binary -out=index.android.bundle.hbc index.android.bundle
+echo -n "  Assembling js bundle into hermes binary to 'index.android.bundle.hbc'..."
+./node_modules/hermes-engine/linux64-bin/hermesc -O -emit-binary -out=index.android.bundle.hbc index.android.bundle > ./hbcgen_logs/bundle_to_hbc_binary.log 2>&1
 if [ ! $? ]
   then
-    echo "Error: Failed to assemble js into hermes binary"
+    echo; echo "Error: Failed to assemble js into hermes binary, see logs in '$1/hbcgen_logs/bundle_to_hbc_binary.log'"
     exit 1
 fi
+echo " DONE"
 
 # Disassemble hermes binary in readable hermes bytecode
-echo "-------------------------------------------------------------------------"
-echo "Disassembling hermes binary into hermes readable bytecode -->" $3
-echo "-------------------------------------------------------------------------"
-$SCRIPT_DIR/build/bin$PROJ_HBC/hermesc -dump-bytecode index.android.bundle.hbc -out $3
+echo -n "  Disassembling hermes binary into hermes readable bytecode to '$3'..."
+$SCRIPT_DIR/build/bin$PROJ_HBC/hermesc -dump-bytecode index.android.bundle.hbc -out $3 > ./hbcgen_logs/binary_to_hbc.log 2>&1
 if [ ! $? ]
   then
-    echo "Error: Failed to disassemble hermes binary into bytecode"
+    echo; echo "Error: Failed to disassemble hermes binary into bytecode, see logs in '$1/hbcgen_logs/binary_to_hbc.log'"
     exit 1
 fi
+echo " DONE"
 
 echo "HBC Generation successful! Enjoy :)"
 
